// Real KMC ward localities — 1:1 with locations (ward numbers 1-144).
// Updated per user authoritative list (with citations) — 2024 KMC.

export const WARD_LOCALITIES: Record<number, string> = {
  1: "Cossipore",
  2: "Sinthee",
  3: "Belgachia (East) & Duttabagan",
  4: "Paikpara",
  5: "Tala & Belgachia (West)",
  6: "Chitpur",
  7: "Bagbazar",
  8: "Shobhabazar (North)",
  9: "Kumartuli & Shyampukur",
  10: "Shobhabazar (South) & Hatibagan",
  11: "Shyambazar",
  12: "Burtolla",
  13: "Ultadanga",
  14: "Bagmari",
  15: "Maniktala",
  16: "Goabagan",
  17: "Simla",
  18: "Beadon Street",
  19: "Ahiritola",
  20: "Beniatola",
  21: "Jorabagan",
  22: "Posta",
  23: "Pathuriaghata",
  24: "Jorasanko",
  25: "Girish Park",
  26: "Ram Mudar Lane / Vivek Nagar",
  27: "Mechua",
  28: "Kalabagan",
  29: "Narikeldanga (North)",
  30: "Narikeldanga (South)",
  31: "Phoolbagan",
  32: "Kankurgachi",
  33: "Beliaghata (North)",
  34: "Beliaghata (South)",
  35: "Sukanta Nagar / Subhas Sarobar",
  36: "Sealdah",
  37: "Amratala",
  38: "Mirzapur",
  39: "College Street",
  40: "Bowbazar",
  41: "Burrabazar",
  42: "Bara Bazar (South)",
  43: "Fairlie Place / BBD Bagh Central",
  44: "Esplanade / Chandni Chowk",
  45: "Dalhousie / Esplanade West",
  46: "Dharmatala",
  47: "Wellington / Janbazar",
  48: "Muchipara",
  49: "Lebutala",
  50: "Santosh Mitra Square",
  51: "Taltala (North)",
  52: "Taltala (South)",
  53: "Wellesley",
  54: "Entally",
  55: "Ananda Palit",
  56: "Convent Road",
  57: "Dhapa",
  58: "Tangra",
  59: "Gobra",
  60: "Beniapukur",
  61: "Park Circus",
  62: "Rippon Street",
  63: "Mullick Bazar / Theatre Road",
  64: "Park Street",
  65: "Padmapukur",
  66: "Topsia Extended / Tiljala",
  67: "Picnics Garden",
  68: "Ballygunge",
  69: "Ballygunge Circular Road",
  70: "Padmapukur / Sarat Bose Road",
  71: "Bhowanipore",
  72: "Bakulbagan",
  73: "Kalighat",
  74: "Alipore",
  75: "Hastings / Khidirpur (North)",
  76: "Khidirpur (South)",
  77: "Watgunge",
  78: "Mominpore",
  79: "Ekbalpur",
  80: "Garden Reach (BNR Colony)",
  81: "New Alipore",
  82: "Chetla",
  83: "Hazra Road",
  84: "Hazra",
  85: "Deshapriya Park",
  86: "Lake Market",
  87: "Mudiali",
  88: "Tollygunge (North)",
  89: "Charu Market",
  90: "Rabindra Sarobar / Lake Gardens",
  91: "Kasba (North)",
  92: "Dhakuria",
  93: "Jodhpur Park",
  94: "Golf Green",
  95: "Bijoygarh",
  96: "Jadavpur",
  97: "Tollygunge (South)",
  98: "Netaji Nagar",
  99: "Baghajatin",
  100: "Ramgarh",
  101: "Patuli",
  102: "Garia",
  103: "Santoshpur",
  104: "Kalikapur",
  105: "Haltu",
  106: "Kasba (South)",
  107: "Ruby / Anandapur",
  108: "Chowbaga",
  109: "Mukundapur",
  110: "Briji",
  111: "Kamdahari",
  112: "Garia (West)",
  113: "Bansdroni",
  114: "Kudghat",
  115: "Haridevpur",
  116: "Paschim Putiary",
  117: "Keoratala / Kudghat West",
  118: "New Alipore (South)",
  119: "Behala (North)",
  120: "Behala (Roy Bahadur Road)",
  121: "Behala (Mantonton)",
  122: "James Long Sarani",
  123: "Barisha",
  124: "Thakurpukur",
  125: "Joka (North)",
  126: "Joka (South)",
  127: "Parnasree Pally",
  128: "Behala (South)",
  129: "Sarsuna",
  130: "Behala (Chowrashta)",
  131: "Shibrampur",
  132: "Behala (Pathakpara)",
  133: "Metiabruz",
  134: "Garden Reach (Metiabruz West)",
  135: "Mudiali / Garden Reach East",
  136: "Santoshpur (Metiabruz)",
  137: "Akra",
  138: "Bartala",
  139: "Panchur",
  140: "Badartala",
  141: "Karbala (Metiabruz)",
  142: "Ramchandrapur",
  143: "Joka (East)",
  144: "Joka (West)",
};

export function getWardLocality(ward: number | null | undefined): string | null {
  if (ward == null || !Number.isFinite(ward)) return null;
  return WARD_LOCALITIES[ward] ?? null;
}

export function getWardDisplayName(ward: number | null | undefined, fallback?: string | null): string {
  const loc = getWardLocality(ward);
  if (loc && ward != null) return `Ward ${ward} · ${loc}`;
  if (ward != null) return `Ward ${ward}`;
  return fallback ?? "Ward";
}

export function getWardShortName(ward: number | null | undefined): string {
  const loc = getWardLocality(ward);
  if (loc) return loc;
  if (ward != null) return `Ward ${ward}`;
  return "Ward";
}

export function matchesWardQuery(ward: number | null, wardName: string | null, locality: string | null, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return false;
  if (ward != null && String(ward).includes(q)) return true;
  if (ward != null && `ward ${ward}`.includes(q)) return true;
  if (wardName && wardName.toLowerCase().includes(q)) return true;
  if (locality && locality.toLowerCase().includes(q)) return true;
  return false;
}
